services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    container_name: keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: 1234
#    ports:
#      - "8080:8080"
#    command:
#      - start-dev
#    networks:
#      - keycloak-network
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
#    networks:
#      - keycloak-network
#
#networks:
#  keycloak-network:
#    driver: bridge
